import './globals.css'

import type { Metadata } from 'next'

import { pretendard } from '../../public/fonts/fonts'
import Header from '../components/common/Header'
import { cn } from '../lib/utils/cn'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={cn(pretendard.className)}>
        <Header />
        {children}
      </body>
    </html>
  )
}
