import './globals.css'

import type { Metadata } from 'next'

import { cn } from '@/lib/cn'

import { pretendard, sen } from '../../public/fonts/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(pretendard.className, sen.className)}>{children}</body>
    </html>
  )
}
